language: go

go:
# Go 1.2 disabled because it is missing regexp package when using -race flag
#  - 1.2
# Go 1.3 disabled because it is not released yet. Enable when 1.3 is released
#  - 1.3
  - tip

allowed_failures:
  - go: tip

install:
  - go get -d -v ./... && go install -race -v ./...

script: go test -race -v ./...
